'''This file is part of rigol-sourcegui.
   
   Copyright (c) 2017 Márk Vasi

   rigol-sourcegui is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   rigol-sourcegui is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with rigol-sourcegui.  If not, see <http://www.gnu.org/licenses/>.'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(534, 370)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 400))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.channel1 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel1.sizePolicy().hasHeightForWidth())
        self.channel1.setSizePolicy(sizePolicy)
        self.channel1.setObjectName(_fromUtf8("channel1"))
        self.gridLayout = QtGui.QGridLayout(self.channel1)
        self.gridLayout.setMargin(1)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.s1_moreShapes = QtGui.QPushButton(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_moreShapes.sizePolicy().hasHeightForWidth())
        self.s1_moreShapes.setSizePolicy(sizePolicy)
        self.s1_moreShapes.setObjectName(_fromUtf8("s1_moreShapes"))
        self.gridLayout.addWidget(self.s1_moreShapes, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 10, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 8, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 2, 1)
        self.label = QtGui.QLabel(self.channel1)
        self.label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 2, 3)
        self.label_2 = QtGui.QLabel(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.s1_enable = QtGui.QCheckBox(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_enable.sizePolicy().hasHeightForWidth())
        self.s1_enable.setSizePolicy(sizePolicy)
        self.s1_enable.setObjectName(_fromUtf8("s1_enable"))
        self.gridLayout.addWidget(self.s1_enable, 2, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.s1_shape = QtGui.QComboBox(self.channel1)
        self.s1_shape.setObjectName(_fromUtf8("s1_shape"))
        self.s1_shape.addItem(_fromUtf8(""))
        self.s1_shape.addItem(_fromUtf8(""))
        self.s1_shape.addItem(_fromUtf8(""))
        self.s1_shape.addItem(_fromUtf8(""))
        self.s1_shape.addItem(_fromUtf8(""))
        self.s1_shape.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.s1_shape, 3, 1, 1, 2)
        self.s1_v = QtGui.QLineEdit(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_v.sizePolicy().hasHeightForWidth())
        self.s1_v.setSizePolicy(sizePolicy)
        self.s1_v.setText(_fromUtf8(""))
        self.s1_v.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s1_v.setObjectName(_fromUtf8("s1_v"))
        self.gridLayout.addWidget(self.s1_v, 5, 1, 1, 2)
        self.s1_frq = QtGui.QLineEdit(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_frq.sizePolicy().hasHeightForWidth())
        self.s1_frq.setSizePolicy(sizePolicy)
        self.s1_frq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s1_frq.setObjectName(_fromUtf8("s1_frq"))
        self.gridLayout.addWidget(self.s1_frq, 6, 1, 1, 2)
        self.s1_phase = QtGui.QLineEdit(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_phase.sizePolicy().hasHeightForWidth())
        self.s1_phase.setSizePolicy(sizePolicy)
        self.s1_phase.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s1_phase.setObjectName(_fromUtf8("s1_phase"))
        self.gridLayout.addWidget(self.s1_phase, 7, 1, 1, 2)
        self.s1_offset = QtGui.QLineEdit(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_offset.sizePolicy().hasHeightForWidth())
        self.s1_offset.setSizePolicy(sizePolicy)
        self.s1_offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s1_offset.setObjectName(_fromUtf8("s1_offset"))
        self.gridLayout.addWidget(self.s1_offset, 8, 1, 1, 2)
        self.s1_duty = QtGui.QLineEdit(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_duty.sizePolicy().hasHeightForWidth())
        self.s1_duty.setSizePolicy(sizePolicy)
        self.s1_duty.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s1_duty.setObjectName(_fromUtf8("s1_duty"))
        self.gridLayout.addWidget(self.s1_duty, 9, 1, 1, 2)
        self.s1_simm = QtGui.QLineEdit(self.channel1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s1_simm.sizePolicy().hasHeightForWidth())
        self.s1_simm.setSizePolicy(sizePolicy)
        self.s1_simm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s1_simm.setObjectName(_fromUtf8("s1_simm"))
        self.gridLayout.addWidget(self.s1_simm, 10, 1, 1, 2)
        self.horizontalLayout.addWidget(self.channel1)
        self.channel2 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channel2.sizePolicy().hasHeightForWidth())
        self.channel2.setSizePolicy(sizePolicy)
        self.channel2.setObjectName(_fromUtf8("channel2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.channel2)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_12 = QtGui.QLabel(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 3, 0, 2, 1)
        self.label_14 = QtGui.QLabel(self.channel2)
        self.label_14.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setScaledContents(False)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 2, 3)
        self.label_15 = QtGui.QLabel(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 5, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 9, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 11, 0, 1, 1)
        self.s2_enable = QtGui.QCheckBox(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_enable.sizePolicy().hasHeightForWidth())
        self.s2_enable.setSizePolicy(sizePolicy)
        self.s2_enable.setObjectName(_fromUtf8("s2_enable"))
        self.gridLayout_2.addWidget(self.s2_enable, 2, 0, 1, 3)
        self.label_10 = QtGui.QLabel(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 10, 0, 1, 1)
        self.s2_moreShapes = QtGui.QPushButton(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_moreShapes.sizePolicy().hasHeightForWidth())
        self.s2_moreShapes.setSizePolicy(sizePolicy)
        self.s2_moreShapes.setObjectName(_fromUtf8("s2_moreShapes"))
        self.gridLayout_2.addWidget(self.s2_moreShapes, 4, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 4, 1, 1, 1)
        self.s2_v = QtGui.QLineEdit(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_v.sizePolicy().hasHeightForWidth())
        self.s2_v.setSizePolicy(sizePolicy)
        self.s2_v.setText(_fromUtf8(""))
        self.s2_v.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s2_v.setObjectName(_fromUtf8("s2_v"))
        self.gridLayout_2.addWidget(self.s2_v, 5, 1, 1, 2)
        self.s2_shape = QtGui.QComboBox(self.channel2)
        self.s2_shape.setObjectName(_fromUtf8("s2_shape"))
        self.s2_shape.addItem(_fromUtf8(""))
        self.s2_shape.addItem(_fromUtf8(""))
        self.s2_shape.addItem(_fromUtf8(""))
        self.s2_shape.addItem(_fromUtf8(""))
        self.s2_shape.addItem(_fromUtf8(""))
        self.s2_shape.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.s2_shape, 3, 1, 1, 2)
        self.s2_frq = QtGui.QLineEdit(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_frq.sizePolicy().hasHeightForWidth())
        self.s2_frq.setSizePolicy(sizePolicy)
        self.s2_frq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s2_frq.setObjectName(_fromUtf8("s2_frq"))
        self.gridLayout_2.addWidget(self.s2_frq, 6, 1, 1, 2)
        self.s2_phase = QtGui.QLineEdit(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_phase.sizePolicy().hasHeightForWidth())
        self.s2_phase.setSizePolicy(sizePolicy)
        self.s2_phase.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s2_phase.setObjectName(_fromUtf8("s2_phase"))
        self.gridLayout_2.addWidget(self.s2_phase, 7, 1, 1, 2)
        self.s2_offset = QtGui.QLineEdit(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_offset.sizePolicy().hasHeightForWidth())
        self.s2_offset.setSizePolicy(sizePolicy)
        self.s2_offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s2_offset.setObjectName(_fromUtf8("s2_offset"))
        self.gridLayout_2.addWidget(self.s2_offset, 8, 1, 1, 2)
        self.s2_duty = QtGui.QLineEdit(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_duty.sizePolicy().hasHeightForWidth())
        self.s2_duty.setSizePolicy(sizePolicy)
        self.s2_duty.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s2_duty.setObjectName(_fromUtf8("s2_duty"))
        self.gridLayout_2.addWidget(self.s2_duty, 9, 1, 1, 2)
        self.s2_simm = QtGui.QLineEdit(self.channel2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s2_simm.sizePolicy().hasHeightForWidth())
        self.s2_simm.setSizePolicy(sizePolicy)
        self.s2_simm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.s2_simm.setObjectName(_fromUtf8("s2_simm"))
        self.gridLayout_2.addWidget(self.s2_simm, 10, 1, 1, 2)
        self.horizontalLayout.addWidget(self.channel2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 534, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Load = QtGui.QMenu(self.menuBar)
        self.menu_Load.setObjectName(_fromUtf8("menu_Load"))
        self.menu_Edit = QtGui.QMenu(self.menuBar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        MainWindow.setMenuBar(self.menuBar)
        self.action_Open_config = QtGui.QAction(MainWindow)
        self.action_Open_config.setObjectName(_fromUtf8("action_Open_config"))
        self.action_Save_config = QtGui.QAction(MainWindow)
        self.action_Save_config.setObjectName(_fromUtf8("action_Save_config"))
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_Defaults = QtGui.QAction(MainWindow)
        self.action_Defaults.setObjectName(_fromUtf8("action_Defaults"))
        self.actionFrom_Memory = QtGui.QAction(MainWindow)
        self.actionFrom_Memory.setObjectName(_fromUtf8("actionFrom_Memory"))
        self.actionFrom_File = QtGui.QAction(MainWindow)
        self.actionFrom_File.setObjectName(_fromUtf8("actionFrom_File"))
        self.actionIP_Address = QtGui.QAction(MainWindow)
        self.actionIP_Address.setObjectName(_fromUtf8("actionIP_Address"))
        self.actionDefault_Configuration = QtGui.QAction(MainWindow)
        self.actionDefault_Configuration.setObjectName(_fromUtf8("actionDefault_Configuration"))
        self.action_Help = QtGui.QAction(MainWindow)
        self.action_Help.setObjectName(_fromUtf8("action_Help"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menu_File.addAction(self.action_Open_config)
        self.menu_File.addAction(self.action_Save_config)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Load.addAction(self.action_Defaults)
        self.menu_Load.addAction(self.actionFrom_Memory)
        self.menu_Load.addAction(self.actionFrom_File)
        self.menu_Edit.addAction(self.actionIP_Address)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionDefault_Configuration)
        self.menu_Help.addAction(self.action_Help)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Edit.menuAction())
        self.menuBar.addAction(self.menu_Load.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())
        self.label_5.setBuddy(self.s1_phase)
        self.label_4.setBuddy(self.s1_frq)
        self.label_8.setBuddy(self.s1_simm)
        self.label_6.setBuddy(self.s1_offset)
        self.label_3.setBuddy(self.s1_shape)
        self.label.setBuddy(self.s1_enable)
        self.label_2.setBuddy(self.s1_v)
        self.label_7.setBuddy(self.s1_duty)
        self.label_12.setBuddy(self.s2_offset)
        self.label_13.setBuddy(self.s2_shape)
        self.label_14.setBuddy(self.s2_enable)
        self.label_15.setBuddy(self.s2_v)
        self.label_16.setBuddy(self.s2_duty)
        self.label_10.setBuddy(self.s2_frq)
        self.label_11.setBuddy(self.s2_simm)
        self.label_9.setBuddy(self.s2_phase)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.s1_enable, self.s1_shape)
        MainWindow.setTabOrder(self.s1_shape, self.s1_moreShapes)
        MainWindow.setTabOrder(self.s1_moreShapes, self.s1_v)
        MainWindow.setTabOrder(self.s1_v, self.s1_frq)
        MainWindow.setTabOrder(self.s1_frq, self.s1_phase)
        MainWindow.setTabOrder(self.s1_phase, self.s1_offset)
        MainWindow.setTabOrder(self.s1_offset, self.s1_duty)
        MainWindow.setTabOrder(self.s1_duty, self.s1_simm)
        MainWindow.setTabOrder(self.s1_simm, self.s2_enable)
        MainWindow.setTabOrder(self.s2_enable, self.s2_shape)
        MainWindow.setTabOrder(self.s2_shape, self.s2_moreShapes)
        MainWindow.setTabOrder(self.s2_moreShapes, self.s2_v)
        MainWindow.setTabOrder(self.s2_v, self.s2_frq)
        MainWindow.setTabOrder(self.s2_frq, self.s2_phase)
        MainWindow.setTabOrder(self.s2_phase, self.s2_offset)
        MainWindow.setTabOrder(self.s2_offset, self.s2_duty)
        MainWindow.setTabOrder(self.s2_duty, self.s2_simm)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Source Configuration", None))
        self.s1_moreShapes.setText(_translate("MainWindow", "More...", None))
        self.label_5.setText(_translate("MainWindow", "Phase", None))
        self.label_4.setText(_translate("MainWindow", "Frequency", None))
        self.label_8.setText(_translate("MainWindow", "Symmetry[%]", None))
        self.label_6.setText(_translate("MainWindow", "DC offset", None))
        self.label_3.setText(_translate("MainWindow", "Shape", None))
        self.label.setText(_translate("MainWindow", "Channel &1", None))
        self.label_2.setText(_translate("MainWindow", "Voltage", None))
        self.label_7.setText(_translate("MainWindow", "Duty[%]", None))
        self.s1_enable.setText(_translate("MainWindow", "Enable", None))
        self.s1_shape.setItemText(0, _translate("MainWindow", "Sinusoid", None))
        self.s1_shape.setItemText(1, _translate("MainWindow", "Square", None))
        self.s1_shape.setItemText(2, _translate("MainWindow", "Ramp", None))
        self.s1_shape.setItemText(3, _translate("MainWindow", "Pulse", None))
        self.s1_shape.setItemText(4, _translate("MainWindow", "Noise", None))
        self.s1_shape.setItemText(5, _translate("MainWindow", "More...", None))
        self.label_12.setText(_translate("MainWindow", "DC offset", None))
        self.label_13.setText(_translate("MainWindow", "Shape", None))
        self.label_14.setText(_translate("MainWindow", "Channel &2", None))
        self.label_15.setText(_translate("MainWindow", "Voltage", None))
        self.label_16.setText(_translate("MainWindow", "Duty[%]", None))
        self.s2_enable.setText(_translate("MainWindow", "Enable", None))
        self.label_10.setText(_translate("MainWindow", "Frequency", None))
        self.label_11.setText(_translate("MainWindow", "Symmetry[%]", None))
        self.s2_moreShapes.setText(_translate("MainWindow", "More...", None))
        self.label_9.setText(_translate("MainWindow", "Phase", None))
        self.s2_shape.setItemText(0, _translate("MainWindow", "Sinusoid", None))
        self.s2_shape.setItemText(1, _translate("MainWindow", "Square", None))
        self.s2_shape.setItemText(2, _translate("MainWindow", "Ramp", None))
        self.s2_shape.setItemText(3, _translate("MainWindow", "Pulse", None))
        self.s2_shape.setItemText(4, _translate("MainWindow", "Noise", None))
        self.s2_shape.setItemText(5, _translate("MainWindow", "More...", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Load.setTitle(_translate("MainWindow", "&Load", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help", None))
        self.action_Open_config.setText(_translate("MainWindow", "&Open config", None))
        self.action_Save_config.setText(_translate("MainWindow", "&Save config", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_Defaults.setText(_translate("MainWindow", "&Defaults", None))
        self.actionFrom_Memory.setText(_translate("MainWindow", "From Memory", None))
        self.actionFrom_File.setText(_translate("MainWindow", "From File", None))
        self.actionIP_Address.setText(_translate("MainWindow", "IP Address", None))
        self.actionDefault_Configuration.setText(_translate("MainWindow", "Default Configuration", None))
        self.action_Help.setText(_translate("MainWindow", "&Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

